# Generated by Django 6.0.4 on 2026-04-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_date_of_birth'),
    ]

    operations = [
    ]
